"""compress_notifications_table

Revision ID: 8c8688e9fb4c
Revises: 28161c9e19ba
Create Date: 2025-07-11 21:00:14.677161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8688e9fb4c'
down_revision: Union[str, None] = '28161c9e19ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notifications_post_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_comment_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'post_id')
    op.drop_column('notifications', 'comment_id')
    op.drop_column('notifications', 'actor_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('actor_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('notifications_comment_id_fkey'), 'notifications', 'comments', ['comment_id'], ['id'])
    op.create_foreign_key(op.f('notifications_post_id_fkey'), 'notifications', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
