"""remove_art_request_id_from_reviews

Revision ID: 8eb7ac79c853
Revises: 664d09695f6f
Create Date: 2025-07-11 23:06:47.026009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb7ac79c853'
down_revision: Union[str, None] = '664d09695f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reviews_art_request_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'art_request_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('art_request_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('reviews_art_request_id_fkey'), 'reviews', 'art_requests', ['art_request_id'], ['id'])
    # ### end Alembic commands ###
