"""add_upvote_table_remove_upvotes_column

Revision ID: aa2a73f2ae3f
Revises: 8eb7ac79c853
Create Date: 2025-07-12 11:33:49.082000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2a73f2ae3f'
down_revision: Union[str, None] = '8eb7ac79c853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'upvotes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
