"""Initial migration

Revision ID: edbb9477759d
Revises: 
Create Date: 2025-07-11 18:52:41.725052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edbb9477759d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('follows_follower_id_following_id_key'), 'follows', type_='unique')
    op.drop_index(op.f('idx_follows_follower_id'), table_name='follows')
    op.drop_index(op.f('idx_follows_following_id'), table_name='follows')
    op.create_index(op.f('ix_follows_id'), 'follows', ['id'], unique=False)
    op.drop_constraint(op.f('follows_following_id_fkey'), 'follows', type_='foreignkey')
    op.drop_constraint(op.f('follows_follower_id_fkey'), 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'follows', 'users', ['following_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key(op.f('follows_follower_id_fkey'), 'follows', 'users', ['follower_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('follows_following_id_fkey'), 'follows', 'users', ['following_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_follows_id'), table_name='follows')
    op.create_index(op.f('idx_follows_following_id'), 'follows', ['following_id'], unique=False)
    op.create_index(op.f('idx_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.create_unique_constraint(op.f('follows_follower_id_following_id_key'), 'follows', ['follower_id', 'following_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
