"""Add comment notifications support

Revision ID: ef0607591efd
Revises: edbb9477759d
Create Date: 2025-07-11 20:11:45.581605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0607591efd'
down_revision: Union[str, None] = 'edbb9477759d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_follow', 'follows', ['follower_id', 'following_id'])
    op.add_column('notifications', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'comment_id')
    op.drop_constraint('unique_follow', 'follows', type_='unique')
    # ### end Alembic commands ###
